name: "Merged to Release"

on:
  pull_request:
    branches:
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v
      - run: echo "github actions test"