name: "Merged to Release"

on:
  pull_request:
    branches:
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Check if GITHUB_TOKEN is available
        run: echo "${{ secrets.GITHUB_TOKEN != '' && 'GITHUB_TOKEN OK' || 'MISSING GITHUB_TOKEN' }}"

