name: "Merged to Release"

on:
  pull_request:
    branches:
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name : pnpm
        run: npm install -g pnpm

      - name: Confirm pnpm is available
        run: pnpm --version

      - name: Create package.json if missing
        run: |
          if [ ! -f package.json ]; then
            pnpm init
          fi

      - name: add core,github
        run: pnpm add @actions/core @actions/github

      - name: Install dependencies
        run: pnpm install

      - name: Run append script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${{ secrets.GITHUB_TOKEN }}
          node .github/scripts/pr.js \
            --github-token "$GITHUB_TOKEN" \
            --feature-branch "${{ github.event.pull_request.head.ref }}"