name: "Merged to Release"

on:
  pull_request:
    branches:
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable and activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.1.4 --activate

      - name: Verify pnpm
        run: pnpm --version

      - name: Create package.json
        run: pnpm init -y

      - name: Install dependencies
        run: pnpm install

      - name: Run append script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node .github/scripts/pr.js \
            --github-token "$GITHUB_TOKEN" \
            --feature-branch "${{ github.event.pull_request.head.ref }}"
